using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ProjectEuler
{
    /// <summary>
    //Even Fibonacci numbers
    //Problem 2
    //Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

    //1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    //By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    /// </summary>
    public class Problem002
    {
        public static ulong Answer { get; private set; }

        public static void Solve(int maxSequenceTerm = 4000000)
        {
            Problem002.Answer = 0;

            int term1 = 1;
            int term2 = 2;
            int tempTerm;

            while (term2 <= maxSequenceTerm)
            {
                if (term2 % 2 == 0)
                {
                    Problem002.Answer = checked(Problem002.Answer + (ulong)term2);
                }

                tempTerm = term1;
                term1 = term2;
                term2 = tempTerm + term2;
            }
        }
    }
}
